[features]
seeds = false
[programs.localnet]
kedgeree = "kedgrkbZ5TcjRz2fSpZMcasWzyxd8SuEaXoGfbkPddc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aankor/.config/solana/id.json"

[scripts]
test = "pnpm _test"
